name: create Docker
run-name: ${{ github.actor }} is starting release process 🚀
on: [workflow_dispatch]
jobs:
  login:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with: 
            registry: cr.yandex
            username: json_key
            password: ${{ secrets.YC_REGISTRY}}
      - run: npm run build:docker
      - run: |
            dockerUrl="cr.yandex/crpqfmcpde6ccgipohk3/app:v${{ github.run_number }}"
            docker tag infra-hw $dockerUrl
            docker push $dockerUrl
            docker tag infra-hw "${dockerUrl}_latest"
            docker push "${dockerUrl}_latest"
