name: Deploy
run-name: ${{ github.actor }} is starting release process 🚀
on: 
    workflow_dispatch:
        inputs:
            realice: 
                description: 'Номер версии'
                required: true
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
            cat << 'EOT' > key.json
            ${{ secrets.YC_REGISTRY }}
            EOT
            cat key.json | docker login --username json_key --password-stdin cr.yandex
      - run: docker manifest inspect ${{ secrets.YC_REGISTRY_ID }}/app:v${{ inputs.realice }}
      - run: |
            cat << 'EOT' > ssh_keys
            ${{ secrets.SSH_PRIVATE_KEY }}
            EOT
      - run: |
            cat << 'EOT' > ssh_keys.pub
            ${{ secrets.SSH_PUBLIC_KEY }}
            EOT
      - run: ssh -i ssh_keys -o "IdentitiesOnly=true" -lzaizpr 158.160.140.187 ls
    #   - run: docker pull ${{ secrets.YC_REGISTRY_ID }}/app:v${{ inputs.realice }}
