name: Fix
run-name: ${{ github.actor }} starts fixing action ⚒
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  tests:
    uses: ./.github/workflows/test-and_lint.yml
  addBranch:
    runs-on: ubuntu-latest
    # needs: tests
    permissions:
      issues: write
      contents: write
    steps:
    #   - uses: peter-evans/create-or-update-comment@v4
    #     with:
    #       issue-number: 1
    #       body: |
    #         date: $(date "+%Y-%m-%d")
    #         author: ${{ github.actor }}

    #         - With GitHub **Markdown** :sparkles:
    #         - Created by [create-or-update-comment][1]

    #         [1]: https://github.com/peter-evans/create-or-update-comment
    #       reactions: '+1'
      - uses: actions/checkout@v4
      - run: |
              DATE=$(date "+%Y-%m-%d")
              LATEST_TAG=$(git describe --tags --abbrev=0 || true)

              COMMIT_LOG=$(git log $LATEST_TAG..HEAD) //add fix_|number|
              
              BODY="Release date: $DATE\nAuthor: ${{ github.actor }}\nVersion: ${{ github.run_number }}\nCommit log:\n$COMMIT_LOG\nDocker registry url:"
              gh issue create \
                --title "$TITLE" \
                --body "$(echo -e $BODY)"
              
              git tag v${{ github.run_number }}
              
              git config user.name github-actions
              git config user.email github-actions@github.com
              git checkout -b releases/v${{ github.run_number }}
              echo -e "# Version ${{github.run_number }}\n Commit history:\n$COMMIT_LOG\n" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md
              git add CHANGELOG.md
              git commit -m "Release v${{ github.run_number }}"
              git push --tags --set-upstream origin releases/v${{ github.run_number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Release v${{ github.run_number }}
          ASSIGNEES: monalisa,doctocat,hubot
          LABELS: weekly sync,docs-team
      