name: Fix
run-name: ${{ github.actor }} starts fixing action ⚒
on:  
  workflow_dispatch:
        inputs:
            version: 
                description: 'Номер версии'
                required: true
permissions:
  contents: write
jobs:
  tests:
    uses: ./.github/workflows/test-and_lint.yml
  buildDocker:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: git checkout relieses/${{ inputs.version }}
      - run: npm run build:docker
      - run: |
            cat << 'EOT' > key.json
            ${{ secrets.YC_REGISTRY }}
            EOT
            cat key.json | docker login --username json_key --password-stdin cr.yandex
            dockerUrl="${{ secrets.YC_REGISTRY_ID }}3/app:v${{ github.run_number }}"
            docker tag infra-hw $dockerUrl
            docker push $dockerUrl
            docker tag infra-hw "${dockerUrl}_latest"
            docker push "${dockerUrl}_latest"
  addTag: 
    needs: buildDocker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git checkout relieses/${{ inputs.version }}
      - run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || true)          
          
          git config user.name github-actions
          git config user.email github-actions@github.com

          git commit -m "Fix for v${{ inputs.version }}"
          git tag v${{ inputs.version }}_fix#${{ github.run_number }}
          git push --tags --set-upstream origin main
          git checkout -b releases/v${{ inputs.version }}
          git push --tags --set-upstream origin releases/v${{ inputs.version }}
  add-comment:
    needs: addTag
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        run: |
          DATE=$(date "+%Y-%m-%d")
          BODY="Fix date: $DATE\nAuthor: ${{ github.actor }}\nCommit log:\n$COMMIT_LOG\nDocker registry url: "cr.yandex/crpqfmcpde6ccgipohk3/app:${{ inputs.version }}""
          issueNumber=$(gh issue list -S "in:title Release ${{ inputs.version }}" | grep 'Release ${{ inputs.version }}' | awk '{print $1}')
          gh issue comment "$issueNumber" --body "$(echo -e $BODY)"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        
      