name: Release
run-name: ${{ github.actor }} is starting release process 🚀
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  tests:
    uses: ./.github/workflows/test-and_lint.yml
  addBranch:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: npm run build:docker
      - run: |
            cat << 'EOT' > key.json
            ${{ secrets.YC_REGISTRY }}
            EOT
            cat key.json | docker login --username json_key --password-stdin cr.yandex
            dockerUrl="${{ secrets.YC_REGISTRY_ID }}3/app:v${{ github.run_number }}"
            docker tag infra-hw $dockerUrl
            docker push $dockerUrl
            docker tag infra-hw "${dockerUrl}_latest"
            docker push "${dockerUrl}_latest"
      - run: |
              DATE=$(date "+%Y-%m-%d")
              LATEST_TAG=$(git describe --tags --abbrev=0 || true)

              if [ "$LATEST_TAG" = "" ]; then
                COMMIT_LOG=$(git log HEAD --all)
                echo "Gathering commit log from head"
              else 
                COMMIT_LOG=$(git log $LATEST_TAG..HEAD --all)
                echo "Gathering commit log from $LATEST_TAG to HEAD"
              fi
              
              BODY="Release date: $DATE\nAuthor: ${{ github.actor }}\nVersion: ${{ github.run_number }}\nCommit log:\n$COMMIT_LOG\nDocker registry url: "${{ secrets.YC_REGISTRY_ID }}3/app:v${{ github.run_number }}""
              gh issue create \
                --title "$TITLE" \
                --body "$(echo -e $BODY)"
              
              git tag v${{ github.run_number }}
              
              git config user.name github-actions
              git config user.email github-actions@github.com
              echo -e "# Version ${{github.run_number }}\n Commit history:\n$COMMIT_LOG\n" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md
              git add CHANGELOG.md
              git checkout -b releases/v${{ github.run_number }}
              git commit -m "Release v${{ github.run_number }}"
              git push --tags --set-upstream origin releases/v${{ github.run_number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Release v${{ github.run_number }}
          ASSIGNEES: monalisa,doctocat,hubot
          LABELS: weekly sync,docs-team
      
